import { cache } from "react";
import { shopTheLook } from "@/config/curations";
import { connectDb } from "@/lib/db";
import { SiteEditorialConfig } from "@/models/SiteEditorialConfig";
import { DEFAULT_HERO_SLIDES, type HeroSlideConfig } from "@/config/home-editorial-defaults";
import type { SiteEditorialConfigLean } from "@/models/SiteEditorialConfig";
import { buildAutoImageAlt, sanitizeAltText } from "@/lib/image-alt";

const SITE_ID = "site";

const MARKETING_DEFAULTS = {
  sidebarSeasonalGuidesLabel: "Seasonal guides",
  sidebarNewsletterKicker: "Newsletter",
  sidebarNewsletterTitle: "Saturday styling letter",
  sidebarNewsletterDek: "Room formulas, shopping edits, and quiet-luxury notes — weekly.",
  homepageTrustTitle: "Built for search, saves, and serious readers",
  homepageTrustBody:
    "{siteName} publishes long-form, magazine-quality stories with structured FAQs, rich imagery, and internal links between categories — the kind of depth search engines and Pinterest audiences reward. Our layouts leave room for premium ad experiences without breaking editorial rhythm.",
  relatedStoriesTitle: "Related stories",
  categoryPopularSearchesTitle: "Popular searches in {category}",
  categoryRelatedStoriesTitle: "Popular reads in {category}",
  newsletterReadersSayTitle: "What our readers say",
  searchIntroEyebrow: "Search the library",
  searchIntroTitle: "Find your next room story",
  searchIntroDek: "Search articles, tags, and room guides. Use filters to narrow by category or tag.",
  searchTrendingTitle: "Trending now",
} as const;

function pickMarketingStr(raw: unknown, fallback: string): string {
  const s = String(raw ?? "").trim();
  return s || fallback;
}

function normalizeSlugList(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((s) => String(s || "").trim()).filter(Boolean);
}

function defaultShopTheLook(): ShopTheLookItem[] {
  return shopTheLook.map((x) => {
    const manual = "";
    const auto = buildAutoImageAlt({ cardTitle: x.title, cardCaption: x.caption }, x.image);
    return {
      title: x.title,
      caption: x.caption,
      href: x.href,
      image: x.image,
      imageAlt: manual,
      imageAutoAlt: auto,
    };
  });
}

function normalizeShopTheLook(raw: unknown): ShopTheLookItem[] {
  if (!Array.isArray(raw) || raw.length === 0) return defaultShopTheLook();
  const out: ShopTheLookItem[] = [];
  for (const row of raw) {
    if (!row || typeof row !== "object") continue;
    const o = row as Record<string, unknown>;
    const title = String(o.title || "").trim();
    const image = String(o.image || "").trim();
    if (!title || !image) continue;
    const caption = String(o.caption || "").trim();
    const manual = sanitizeAltText(String(o.imageAlt ?? ""));
    const auto = buildAutoImageAlt({ cardTitle: title, cardCaption: caption }, image);
    out.push({
      title,
      caption,
      href: String(o.href || "/").trim() || "/",
      image,
      imageAlt: manual,
      imageAutoAlt: auto,
    });
  }
  return out.length ? out : defaultShopTheLook();
}

export type ShopTheLookItem = {
  title: string;
  caption: string;
  href: string;
  image: string;
  imageAlt: string;
  imageAutoAlt: string;
};

function normalizeHeroSlides(raw: unknown): HeroSlideConfig[] {
  if (!Array.isArray(raw) || raw.length === 0) return DEFAULT_HERO_SLIDES;
  const out: HeroSlideConfig[] = [];
  for (const row of raw) {
    if (!row || typeof row !== "object") continue;
    const o = row as Record<string, unknown>;
    const src = String(o.src || "").trim();
    if (!src) continue;
    const kicker = String(o.kicker || "");
    const headline = String(o.headline || "");
    const dek = String(o.dek || "");
    const manual = sanitizeAltText(String(o.alt || ""));
    const autoGeneratedAlt = buildAutoImageAlt({ slideKicker: kicker, slideHeadline: headline, slideDek: dek }, src);
    out.push({
      src,
      alt: manual,
      autoGeneratedAlt,
      href: String(o.href || "/"),
      kicker,
      headline,
      dek: String(o.dek || ""),
      detail: String(o.detail || ""),
    });
  }
  return out.length ? out : DEFAULT_HERO_SLIDES;
}

export type HomeEditorialResolved = {
  heroSlides: HeroSlideConfig[];
  shopTheLookItems: ShopTheLookItem[];
  leadStorySlug: string;
  featuredWeeklySlugs: string[];
  featuredDailySlugs: string[];
  featuredMonthlySlugs: string[];
  editorsChoiceSlugs: string[];
  moodRailTitle: string;
  moodRailDek: string;
  moodRailSlugs: string[];
  inspirationFeedTitle: string;
  inspirationFeedDek: string;
  inspirationPinnedSlugs: string[];
  sectionFeaturedWeekTitle: string;
  sectionFeaturedWeekDek: string;
  sectionDailyTitle: string;
  sectionDailyDek: string;
  sectionMonthlyTitle: string;
  sectionMonthlyDek: string;
  sectionEditorsChoiceTitle: string;
  sectionEditorsChoiceDek: string;
  sectionMostPinnedTitle: string;
  sectionMostPinnedDek: string;
  sectionFreshEditorsTitle: string;
  sidebarSeasonalGuidesLabel: string;
  sidebarNewsletterKicker: string;
  sidebarNewsletterTitle: string;
  sidebarNewsletterDek: string;
  homepageTrustTitle: string;
  homepageTrustBody: string;
  relatedStoriesTitle: string;
  categoryPopularSearchesTitle: string;
  categoryRelatedStoriesTitle: string;
  newsletterReadersSayTitle: string;
  searchIntroEyebrow: string;
  searchIntroTitle: string;
  searchIntroDek: string;
  searchTrendingTitle: string;
};

function mapDocToResolved(d: SiteEditorialConfigLean | Record<string, never>): HomeEditorialResolved {
  return {
    heroSlides: normalizeHeroSlides(d.heroSlides),
    shopTheLookItems: normalizeShopTheLook(d.shopTheLookItems),
    leadStorySlug: String(d.leadStorySlug || "").trim(),
    featuredWeeklySlugs: normalizeSlugList(d.featuredWeeklySlugs),
    featuredDailySlugs: normalizeSlugList(d.featuredDailySlugs),
    featuredMonthlySlugs: normalizeSlugList(d.featuredMonthlySlugs),
    editorsChoiceSlugs: normalizeSlugList(d.editorsChoiceSlugs),
    moodRailTitle: String(d.moodRailTitle || "").trim(),
    moodRailDek: String(d.moodRailDek || "").trim(),
    moodRailSlugs: normalizeSlugList(d.moodRailSlugs),
    inspirationFeedTitle: String(d.inspirationFeedTitle || "").trim(),
    inspirationFeedDek: String(d.inspirationFeedDek || "").trim(),
    inspirationPinnedSlugs: normalizeSlugList(d.inspirationPinnedSlugs),
    sectionFeaturedWeekTitle: String(d.sectionFeaturedWeekTitle || "").trim(),
    sectionFeaturedWeekDek: String(d.sectionFeaturedWeekDek || "").trim(),
    sectionDailyTitle: String(d.sectionDailyTitle || "").trim(),
    sectionDailyDek: String(d.sectionDailyDek || "").trim(),
    sectionMonthlyTitle: String(d.sectionMonthlyTitle || "").trim(),
    sectionMonthlyDek: String(d.sectionMonthlyDek || "").trim(),
    sectionEditorsChoiceTitle: String(d.sectionEditorsChoiceTitle || "").trim(),
    sectionEditorsChoiceDek: String(d.sectionEditorsChoiceDek || "").trim(),
    sectionMostPinnedTitle: String(d.sectionMostPinnedTitle || "").trim(),
    sectionMostPinnedDek: String(d.sectionMostPinnedDek || "").trim(),
    sectionFreshEditorsTitle: String(d.sectionFreshEditorsTitle || "").trim(),
    sidebarSeasonalGuidesLabel: pickMarketingStr(
      d.sidebarSeasonalGuidesLabel,
      MARKETING_DEFAULTS.sidebarSeasonalGuidesLabel,
    ),
    sidebarNewsletterKicker: pickMarketingStr(d.sidebarNewsletterKicker, MARKETING_DEFAULTS.sidebarNewsletterKicker),
    sidebarNewsletterTitle: pickMarketingStr(d.sidebarNewsletterTitle, MARKETING_DEFAULTS.sidebarNewsletterTitle),
    sidebarNewsletterDek: pickMarketingStr(d.sidebarNewsletterDek, MARKETING_DEFAULTS.sidebarNewsletterDek),
    homepageTrustTitle: pickMarketingStr(d.homepageTrustTitle, MARKETING_DEFAULTS.homepageTrustTitle),
    homepageTrustBody: pickMarketingStr(d.homepageTrustBody, MARKETING_DEFAULTS.homepageTrustBody),
    relatedStoriesTitle: pickMarketingStr(d.relatedStoriesTitle, MARKETING_DEFAULTS.relatedStoriesTitle),
    categoryPopularSearchesTitle: pickMarketingStr(
      d.categoryPopularSearchesTitle,
      MARKETING_DEFAULTS.categoryPopularSearchesTitle,
    ),
    categoryRelatedStoriesTitle: pickMarketingStr(
      d.categoryRelatedStoriesTitle,
      MARKETING_DEFAULTS.categoryRelatedStoriesTitle,
    ),
    newsletterReadersSayTitle: pickMarketingStr(
      d.newsletterReadersSayTitle,
      MARKETING_DEFAULTS.newsletterReadersSayTitle,
    ),
    searchIntroEyebrow: pickMarketingStr(d.searchIntroEyebrow, MARKETING_DEFAULTS.searchIntroEyebrow),
    searchIntroTitle: pickMarketingStr(d.searchIntroTitle, MARKETING_DEFAULTS.searchIntroTitle),
    searchIntroDek: pickMarketingStr(d.searchIntroDek, MARKETING_DEFAULTS.searchIntroDek),
    searchTrendingTitle: pickMarketingStr(d.searchTrendingTitle, MARKETING_DEFAULTS.searchTrendingTitle),
  };
}

async function loadEditorialFromDatabase(): Promise<HomeEditorialResolved> {
  let doc: SiteEditorialConfigLean | null = null;
  try {
    await connectDb();
    const row = await SiteEditorialConfig.findById(SITE_ID).lean();
    doc = row ? (JSON.parse(JSON.stringify(row)) as SiteEditorialConfigLean) : null;
  } catch {
    doc = null;
  }
  return mapDocToResolved(doc || {});
}

export const getHomeEditorialResolved = cache(loadEditorialFromDatabase);

export async function upsertSiteEditorialConfig(payload: Partial<HomeEditorialResolved>): Promise<HomeEditorialResolved> {
  const cur = await loadEditorialFromDatabase();
  const merged: HomeEditorialResolved = {
    heroSlides:
      payload.heroSlides !== undefined ? normalizeHeroSlides(payload.heroSlides) : cur.heroSlides,
    shopTheLookItems:
      payload.shopTheLookItems !== undefined
        ? normalizeShopTheLook(payload.shopTheLookItems)
        : cur.shopTheLookItems,
    leadStorySlug: payload.leadStorySlug !== undefined ? String(payload.leadStorySlug || "").trim() : cur.leadStorySlug,
    featuredWeeklySlugs:
      payload.featuredWeeklySlugs !== undefined
        ? normalizeSlugList(payload.featuredWeeklySlugs)
        : cur.featuredWeeklySlugs,
    featuredDailySlugs:
      payload.featuredDailySlugs !== undefined ? normalizeSlugList(payload.featuredDailySlugs) : cur.featuredDailySlugs,
    featuredMonthlySlugs:
      payload.featuredMonthlySlugs !== undefined
        ? normalizeSlugList(payload.featuredMonthlySlugs)
        : cur.featuredMonthlySlugs,
    editorsChoiceSlugs:
      payload.editorsChoiceSlugs !== undefined
        ? normalizeSlugList(payload.editorsChoiceSlugs)
        : cur.editorsChoiceSlugs,
    moodRailTitle: payload.moodRailTitle !== undefined ? String(payload.moodRailTitle || "") : cur.moodRailTitle,
    moodRailDek: payload.moodRailDek !== undefined ? String(payload.moodRailDek || "") : cur.moodRailDek,
    moodRailSlugs:
      payload.moodRailSlugs !== undefined ? normalizeSlugList(payload.moodRailSlugs) : cur.moodRailSlugs,
    inspirationFeedTitle:
      payload.inspirationFeedTitle !== undefined
        ? String(payload.inspirationFeedTitle || "")
        : cur.inspirationFeedTitle,
    inspirationFeedDek:
      payload.inspirationFeedDek !== undefined ? String(payload.inspirationFeedDek || "") : cur.inspirationFeedDek,
    inspirationPinnedSlugs:
      payload.inspirationPinnedSlugs !== undefined
        ? normalizeSlugList(payload.inspirationPinnedSlugs)
        : cur.inspirationPinnedSlugs,
    sectionFeaturedWeekTitle:
      payload.sectionFeaturedWeekTitle !== undefined
        ? String(payload.sectionFeaturedWeekTitle || "")
        : cur.sectionFeaturedWeekTitle,
    sectionFeaturedWeekDek:
      payload.sectionFeaturedWeekDek !== undefined
        ? String(payload.sectionFeaturedWeekDek || "")
        : cur.sectionFeaturedWeekDek,
    sectionDailyTitle:
      payload.sectionDailyTitle !== undefined ? String(payload.sectionDailyTitle || "") : cur.sectionDailyTitle,
    sectionDailyDek:
      payload.sectionDailyDek !== undefined ? String(payload.sectionDailyDek || "") : cur.sectionDailyDek,
    sectionMonthlyTitle:
      payload.sectionMonthlyTitle !== undefined ? String(payload.sectionMonthlyTitle || "") : cur.sectionMonthlyTitle,
    sectionMonthlyDek:
      payload.sectionMonthlyDek !== undefined ? String(payload.sectionMonthlyDek || "") : cur.sectionMonthlyDek,
    sectionEditorsChoiceTitle:
      payload.sectionEditorsChoiceTitle !== undefined
        ? String(payload.sectionEditorsChoiceTitle || "")
        : cur.sectionEditorsChoiceTitle,
    sectionEditorsChoiceDek:
      payload.sectionEditorsChoiceDek !== undefined
        ? String(payload.sectionEditorsChoiceDek || "")
        : cur.sectionEditorsChoiceDek,
    sectionMostPinnedTitle:
      payload.sectionMostPinnedTitle !== undefined
        ? String(payload.sectionMostPinnedTitle || "")
        : cur.sectionMostPinnedTitle,
    sectionMostPinnedDek:
      payload.sectionMostPinnedDek !== undefined
        ? String(payload.sectionMostPinnedDek || "")
        : cur.sectionMostPinnedDek,
    sectionFreshEditorsTitle:
      payload.sectionFreshEditorsTitle !== undefined
        ? String(payload.sectionFreshEditorsTitle || "")
        : cur.sectionFreshEditorsTitle,
    sidebarSeasonalGuidesLabel:
      payload.sidebarSeasonalGuidesLabel !== undefined
        ? String(payload.sidebarSeasonalGuidesLabel || "")
        : cur.sidebarSeasonalGuidesLabel,
    sidebarNewsletterKicker:
      payload.sidebarNewsletterKicker !== undefined
        ? String(payload.sidebarNewsletterKicker || "")
        : cur.sidebarNewsletterKicker,
    sidebarNewsletterTitle:
      payload.sidebarNewsletterTitle !== undefined
        ? String(payload.sidebarNewsletterTitle || "")
        : cur.sidebarNewsletterTitle,
    sidebarNewsletterDek:
      payload.sidebarNewsletterDek !== undefined
        ? String(payload.sidebarNewsletterDek || "")
        : cur.sidebarNewsletterDek,
    homepageTrustTitle:
      payload.homepageTrustTitle !== undefined ? String(payload.homepageTrustTitle || "") : cur.homepageTrustTitle,
    homepageTrustBody:
      payload.homepageTrustBody !== undefined ? String(payload.homepageTrustBody || "") : cur.homepageTrustBody,
    relatedStoriesTitle:
      payload.relatedStoriesTitle !== undefined ? String(payload.relatedStoriesTitle || "") : cur.relatedStoriesTitle,
    categoryPopularSearchesTitle:
      payload.categoryPopularSearchesTitle !== undefined
        ? String(payload.categoryPopularSearchesTitle || "")
        : cur.categoryPopularSearchesTitle,
    categoryRelatedStoriesTitle:
      payload.categoryRelatedStoriesTitle !== undefined
        ? String(payload.categoryRelatedStoriesTitle || "")
        : cur.categoryRelatedStoriesTitle,
    newsletterReadersSayTitle:
      payload.newsletterReadersSayTitle !== undefined
        ? String(payload.newsletterReadersSayTitle || "")
        : cur.newsletterReadersSayTitle,
    searchIntroEyebrow:
      payload.searchIntroEyebrow !== undefined ? String(payload.searchIntroEyebrow || "") : cur.searchIntroEyebrow,
    searchIntroTitle:
      payload.searchIntroTitle !== undefined ? String(payload.searchIntroTitle || "") : cur.searchIntroTitle,
    searchIntroDek:
      payload.searchIntroDek !== undefined ? String(payload.searchIntroDek || "") : cur.searchIntroDek,
    searchTrendingTitle:
      payload.searchTrendingTitle !== undefined ? String(payload.searchTrendingTitle || "") : cur.searchTrendingTitle,
  };

  await connectDb();
  await SiteEditorialConfig.findOneAndUpdate(
    { _id: SITE_ID },
    {
      $set: {
        heroSlides: merged.heroSlides,
        shopTheLookItems: merged.shopTheLookItems,
        leadStorySlug: merged.leadStorySlug || undefined,
        featuredWeeklySlugs: merged.featuredWeeklySlugs,
        featuredDailySlugs: merged.featuredDailySlugs,
        featuredMonthlySlugs: merged.featuredMonthlySlugs,
        editorsChoiceSlugs: merged.editorsChoiceSlugs,
        moodRailTitle: merged.moodRailTitle || undefined,
        moodRailDek: merged.moodRailDek || undefined,
        moodRailSlugs: merged.moodRailSlugs,
        inspirationFeedTitle: merged.inspirationFeedTitle || undefined,
        inspirationFeedDek: merged.inspirationFeedDek || undefined,
        inspirationPinnedSlugs: merged.inspirationPinnedSlugs,
        sectionFeaturedWeekTitle: merged.sectionFeaturedWeekTitle || undefined,
        sectionFeaturedWeekDek: merged.sectionFeaturedWeekDek || undefined,
        sectionDailyTitle: merged.sectionDailyTitle || undefined,
        sectionDailyDek: merged.sectionDailyDek || undefined,
        sectionMonthlyTitle: merged.sectionMonthlyTitle || undefined,
        sectionMonthlyDek: merged.sectionMonthlyDek || undefined,
        sectionEditorsChoiceTitle: merged.sectionEditorsChoiceTitle || undefined,
        sectionEditorsChoiceDek: merged.sectionEditorsChoiceDek || undefined,
        sectionMostPinnedTitle: merged.sectionMostPinnedTitle || undefined,
        sectionMostPinnedDek: merged.sectionMostPinnedDek || undefined,
        sectionFreshEditorsTitle: merged.sectionFreshEditorsTitle || undefined,
        sidebarSeasonalGuidesLabel: merged.sidebarSeasonalGuidesLabel || undefined,
        sidebarNewsletterKicker: merged.sidebarNewsletterKicker || undefined,
        sidebarNewsletterTitle: merged.sidebarNewsletterTitle || undefined,
        sidebarNewsletterDek: merged.sidebarNewsletterDek || undefined,
        homepageTrustTitle: merged.homepageTrustTitle || undefined,
        homepageTrustBody: merged.homepageTrustBody || undefined,
        relatedStoriesTitle: merged.relatedStoriesTitle || undefined,
        categoryPopularSearchesTitle: merged.categoryPopularSearchesTitle || undefined,
        categoryRelatedStoriesTitle: merged.categoryRelatedStoriesTitle || undefined,
        newsletterReadersSayTitle: merged.newsletterReadersSayTitle || undefined,
        searchIntroEyebrow: merged.searchIntroEyebrow || undefined,
        searchIntroTitle: merged.searchIntroTitle || undefined,
        searchIntroDek: merged.searchIntroDek || undefined,
        searchTrendingTitle: merged.searchTrendingTitle || undefined,
      },
    },
    { upsert: true },
  );

  return mapDocToResolved(merged as unknown as SiteEditorialConfigLean);
}

/** Add or remove a slug from the homepage “Editor’s choice” rail (order preserved except new adds go first). */
export async function toggleEditorsChoiceSlug(articleSlug: string, include: boolean): Promise<void> {
  const s = String(articleSlug || "").trim();
  if (!s) return;
  const cur = await loadEditorialFromDatabase();
  const rest = cur.editorsChoiceSlugs.filter((x) => x !== s);
  const next = include ? [s, ...rest] : rest;
  await upsertSiteEditorialConfig({ editorsChoiceSlugs: next });
}
