export type AdminMediaUploadOptions = {
  /** Manual alt — optional; server still stores auto-generated pair */
  alt?: string;
  /** e.g. article title — improves auto alt when filename is a UUID */
  contextTitle?: string;
  contextCategorySlug?: string;
  showInGallery?: boolean;
  galleryCategory?: string;
};

export type AdminMediaUploadResult = {
  url: string;
  alt?: string;
  autoGeneratedAlt?: string;
  imageMetadata?: { originalFileName?: string };
};

export async function adminUploadMedia(file: File, opts: AdminMediaUploadOptions = {}): Promise<AdminMediaUploadResult> {
  const fd = new FormData();
  fd.set("file", file);
  fd.set("showInGallery", opts.showInGallery ? "1" : "0");
  if (opts.showInGallery && opts.galleryCategory) fd.set("galleryCategory", opts.galleryCategory);
  if (opts.alt?.trim()) fd.set("alt", opts.alt.trim());
  if (opts.contextTitle?.trim()) fd.set("contextTitle", opts.contextTitle.trim());
  if (opts.contextCategorySlug?.trim()) fd.set("contextCategorySlug", opts.contextCategorySlug.trim());

  const res = await fetch("/api/media", { method: "POST", body: fd, credentials: "include" });
  const data = (await res.json().catch(() => ({}))) as AdminMediaUploadResult & { error?: string };
  if (!res.ok) throw new Error(data.error || "Upload failed");
  if (!data.url) throw new Error("Upload succeeded but no image URL was returned.");
  return data;
}
