import mongoose, { Schema } from "mongoose";

const ContentBlock = new Schema(
  {
    type: { type: String, enum: ["paragraph", "heading", "image", "quote", "list"], required: true },
    content: { type: String, required: true },
    level: Number,
    alt: String,
    autoGeneratedAlt: { type: String, default: "" },
  },
  { _id: false },
);

const FAQ = new Schema({ question: String, answer: String }, { _id: false });

const ArticleSchema = new Schema(
  {
    title: { type: String, required: true },
    slug: { type: String, unique: true, index: true },
    excerpt: String,
    featuredImage: String,
    featuredImageAlt: { type: String, default: "" },
    featuredImageAutoAlt: { type: String, default: "" },
    categorySlug: { type: String, index: true },
    subcategorySlug: { type: String, index: true },
    tags: [String],
    contentBlocks: [ContentBlock],
    faq: [FAQ],
    internalLinks: [String],
    authorName: String,
    authorSlug: String,
    status: { type: String, enum: ["draft", "published"], default: "draft", index: true },
    publishedAt: Date,
    scheduledPublishAt: Date,
    readingTime: Number,
    seoTitle: String,
    seoDescription: String,
    focusKeyword: String,
    views: { type: Number, default: 0 },
    popularityScore: { type: Number, default: 0, index: true },
    /** Lower = higher in trending when set (manual slots). Omit for pure popularity ordering. */
    trendingRank: { type: Number, default: undefined },
    /** Omit from /trending and homepage “most pinned” when true */
    excludeFromTrending: { type: Boolean, default: false },
    /** Denormalized from live reviews for fast cards & SEO */
    reviewAverage: { type: Number, default: 0 },
    reviewCount: { type: Number, default: 0 },
  },
  { timestamps: true },
);

ArticleSchema.index({ title: "text", excerpt: "text", tags: "text" });

/**
 * Next.js dev / Turbopack can keep a stale compiled model on hot reload; old schemas strip fields
 * that were added later (e.g. trendingRank). Drop the cache in development.
 */
if (process.env.NODE_ENV !== "production" && mongoose.models.Article) {
  delete mongoose.models.Article;
}

export const Article =
  mongoose.models.Article ?? mongoose.model("Article", ArticleSchema);
