import { Schema, model, models } from "mongoose";

const ImageMetadataSchema = new Schema(
  {
    originalFileName: { type: String, default: "" },
    source: { type: String, default: "admin_upload" },
    lastContextTitle: { type: String, default: "" },
  },
  { _id: false },
);

const MediaUploadSchema = new Schema(
  {
    url: String,
    /** Display alt (manual if provided, else auto) */
    alt: String,
    autoGeneratedAlt: { type: String, default: "" },
    imageMetadata: { type: ImageMetadataSchema, default: undefined },
    width: Number,
    height: Number,
    mimeType: String,
    tags: [String],
    showInGallery: { type: Boolean, default: false },
    galleryCategory: {
      type: String,
      enum: ["living", "kitchen", "bedroom", "bathroom", "wall-decor", "entryway", "general"],
    },
  },
  { timestamps: true },
);

export const MediaUpload = models.MediaUpload || model("MediaUpload", MediaUploadSchema);